#!/bin/bash

# script to retrieve a file via FTP

FTP_SERVER=ftp.nl.devian.org
FTP_PATH=/devian/dists/lenny/main/installer-i386/current/images/cdrom
REMOTE_FILE=devian-cd_info.tar.gz

ftp -n <<- _EOF_
	open $FTP_SERVER
	user anonymous me@linuxbox
	cd $FTP_PATH
	hash
	get $REMOTE_FILE
	bye
	_EOF_
ls -l $REMOTE_FILE

